explicit template instantiation for base class BasePullQueue
Without it, when enabling -O3 optimizations, the following error occurs:

    .../sim/fairpullqueue.h:46: undefined reference to `BasePullQueue<NdpPull>::~BasePullQueue()'

Apparently, the explicit instantiation of subclasses only causes an
implicit instantiation of the base, which includes its declaration, but
not every definition. See https://stackoverflow.com/q/3705000 for
discussion.